### ISSUE TITLE
파비콘 없음

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/gradient#1]
![image](https://user-images.githubusercontent.com/5790535/117608019-335fe500-b198-11eb-84a4-3d7fc3b206f9.png)

**Comment by easylogic** [comment]
괜찮은 이미지를 하나 생각해봐야겠습니다.

**Comment by easylogic** [comment]
파비콘 적용했습니다. ^^

**Comment by hikaMaeng** [comment]
파비콘 촌스러움. 재 작업 요청
