### ISSUE TITLE
컬러피커 오작동

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/gradient#10]
![image](https://user-images.githubusercontent.com/5790535/118477299-7fd39380-b749-11eb-9d20-5a09d6cdd748.png)

배경에서 컬러피커를 그라데이션으로 사용후

보더에서 컬러피커를 사용하면 컬러피커가 초기화되어있지 않음

**Comment by easylogic** [comment]
이건 수정 되었습니다.
