### ISSUE TITLE
ui깨짐

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/gradient#12]
![image](https://user-images.githubusercontent.com/5790535/118478808-43089c00-b74b-11eb-9599-54e5fc0a2b42.png)

**Comment by easylogic** [comment]
아 이건 깨지는건 아니고 밑에 넣자니 공간이 너무 없는 것 같아서 일부러 그냥 뒀어요 ㅋㅋㅋ

**Comment by easylogic** [comment]
디자인 동선을 바꾸고 있습니다.  ^^
