### ISSUE TITLE
ui선택문제

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/gradient#13]
![image](https://user-images.githubusercontent.com/5790535/119307461-b019b580-bca6-11eb-85fc-0f6bffc8a656.png)

우측 컬러선택상태에서
다시 좌측 레이어를 골라보면 원클릭에 안되고
두번 눌러야 선택됨

**Comment by easylogic** [comment]
왼쪽 그라디언트 전체 선택 가능 변경하였습니다.
