### ISSUE TITLE
크롬에서 레이아웃 깨짐

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/gradient#2]
![image](https://user-images.githubusercontent.com/5790535/117608091-538fa400-b198-11eb-8d73-71686b54358f.png)

**Comment by hikaMaeng** [comment]
아니 혹시나 해서 엣지에서도 테스트했는데 동일함

![image](https://user-images.githubusercontent.com/5790535/117608248-a9644c00-b198-11eb-841f-b4d4a6e05d37.png)

**Comment by easylogic** [comment]
폰트 사이즈 때문에 다 밀렸네요. 윈도우에서는 기본 폰트 사이즈 크기가 안 맞아서 폰트를 조금 줄였습니다.
