### ISSUE TITLE
잘못된 아이콘

### ISSUE THREAD

**Issue by hikaMaeng** [easylogic/gradient#3]
![image](https://user-images.githubusercontent.com/5790535/118069626-76f86000-b3df-11eb-8a90-48dbe29c0952.png)
여기에 화살표는 이상한듯

**Comment by easylogic** [comment]
동일하게 맞추는 버튼인데 ㅋ 모양을 바꿔야겠습니다.

**Comment by easylogic** [comment]
그냥 = 기호로 바꿨습니다. 적당한게 없네요. ^^;;;;;
